part1_fasta_path: "/Users/deepanshu/Documents/NLP_6120/Assignements/A1/test_files-2/test_part1_in.fasta"

part2_fasta_path: "/Users/deepanshu/Documents/NLP_6120/Assignements/A1/test_files-2/test_part2_in.fasta"